<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.METODOS | TRABAJO DE CALIDAD DE AGUA RIMAC</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="3.METODOS | TRABAJO DE CALIDAD DE AGUA RIMAC" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.METODOS | TRABAJO DE CALIDAD DE AGUA RIMAC" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Yihui Xie" />


<meta name="date" content="2021-03-30" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="objetivos.html"/>
<link rel="next" href="applications.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>1.DATOS</a></li>
<li class="chapter" data-level="" data-path="introduccion.html"><a href="introduccion.html"><i class="fa fa-check"></i>1.INTRODUCCION</a></li>
<li class="chapter" data-level="" data-path="objetivos.html"><a href="objetivos.html"><i class="fa fa-check"></i>2.OBJETIVOS</a></li>
<li class="chapter" data-level="" data-path="metodos.html"><a href="metodos.html"><i class="fa fa-check"></i>3.METODOS</a></li>
<li class="chapter" data-level="1" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>1</b> Applications</a>
<ul>
<li class="chapter" data-level="1.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>1.1</b> Example one</a></li>
<li class="chapter" data-level="1.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>1.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>2</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">TRABAJO DE CALIDAD DE AGUA RIMAC</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="metodos" class="section level1 unnumbered">
<h1>3.METODOS</h1>
<p><strong>3.1APLICANDO CLUSTER JERARQUICO</strong></p>
<p><strong><em>AGRUPAMIENTO DE INDIVIDUOS</em></strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="metodos.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="metodos.html#cb1-2" aria-hidden="true" tabindex="-1"></a>datosc <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data_media.xlsx&quot;</span>)</span></code></pre></div>
<p>Estructura:
Tenemos 24 variables de formato numerico y 1 variable en formato character(meses)</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="metodos.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datosc)</span></code></pre></div>
<pre><code>## tibble [12 x 25] (S3: tbl_df/tbl/data.frame)
##  $ meses: chr [1:12] &quot;Ene&quot; &quot;Feb&quot; &quot;Mar&quot; &quot;Abr&quot; ...
##  $ Caud : num [1:12] 40.6 56 71.9 47.6 26.3 23.1 23.5 21.7 22.8 22.4 ...
##  $ Temp : num [1:12] 19.2 20.2 20.2 20.1 18.5 17.2 16.6 15.7 16.5 18.6 ...
##  $ pH   : num [1:12] 7.7 7.8 7 7 8 7 7.8 7 7 8 ...
##  $ Turb : num [1:12] 47.2 301.9 391.7 100.4 12.5 ...
##  $ CE   : num [1:12] 488 440 402 426 595 ...
##  $ OD   : num [1:12] 8.7 8.84 8.94 8.51 8.55 8.64 9 8.76 8.7 8.64 ...
##  $ SD   : num [1:12] 338 308 278 284 380 ...
##  $ Akal : num [1:12] 95.6 91 81.6 91.3 120.4 ...
##  $ DI   : num [1:12] 211 189 165 176 255 ...
##  $ Cls  : num [1:12] 14.3 12.8 12.8 11.9 21.8 24.8 18.8 19.3 19.9 17.8 ...
##  $ so   : num [1:12] 138.6 116.5 97.5 114.6 146.7 ...
##  $ N03  : num [1:12] 2.98 2.78 2.54 2.41 3.38 3.64 3.83 3.58 3.61 3.38 ...
##  $ N02  : num [1:12] 0.2 0.13 0.08 0.1 0.21 0.3 0.23 0.28 0.18 0.24 ...
##  $ PO   : num [1:12] 0.2 0.14 0.09 0.18 0.23 0.28 0.32 0.38 0.36 0.34 ...
##  $ Cu   : num [1:12] 0.04 0.065 0.077 0.038 0.03 0.027 0.022 0.025 0.028 0.023 ...
##  $ Al   : num [1:12] 1.707 7.207 10.89 3.644 0.408 ...
##  $ Fe   : num [1:12] 2.176 7.595 11.37 4.471 0.434 ...
##  $ Mu   : num [1:12] 0.118 0.324 0.342 0.173 0.111 0.089 0.074 0.064 0.049 0.045 ...
##  $ Pb   : num [1:12] 0.024 0.081 0.079 0.056 0.015 0.02 0.013 0.015 0.022 0.012 ...
##  $ Cd   : num [1:12] 0.002 0.005 0.003 0.002 0.003 0.002 0.002 0.002 0.002 0.001 ...
##  $ Zn   : num [1:12] 0.372 0.611 0.641 0.343 0.468 0.323 0.273 0.28 0.28 0.171 ...
##  $ As   : num [1:12] 0.029 0.126 0.088 0.074 0.024 0.023 0.022 0.019 0.022 0.022 ...
##  $ Colo : num [1:12] 178600 247014 208035 174967 160299 ...
##  $ Cole : num [1:12] 74326 95332 90325 58096 63802 ...</code></pre>
<p>Convirtiendo en un dataframe:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="metodos.html#cb4-1" aria-hidden="true" tabindex="-1"></a>datosc<span class="ot">=</span><span class="fu">as.data.frame</span>(datosc)</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="metodos.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(datosc)<span class="ot">&lt;-</span> datosc<span class="sc">$</span>meses</span></code></pre></div>
<p>Eliminanos la variable meses(cualitativa)</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="metodos.html#cb6-1" aria-hidden="true" tabindex="-1"></a>datosc<span class="sc">$</span>meses<span class="ot">=</span><span class="cn">NULL</span></span>
<span id="cb6-2"><a href="metodos.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datosc,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##     Caud Temp  pH  Turb     CE   OD     SD Akal    DI  Cls    so  N03  N02   PO
## Ene 40.6 19.2 7.7  47.2 487.71 8.70 337.86 95.6 211.4 14.3 138.6 2.98 0.20 0.20
## Feb 56.0 20.2 7.8 301.9 440.00 8.84 307.96 91.0 189.1 12.8 116.5 2.78 0.13 0.14
## Mar 71.9 20.2 7.0 391.7 401.96 8.94 278.04 81.6 164.6 12.8  97.5 2.54 0.08 0.09
##        Cu     Al     Fe    Mu    Pb    Cd    Zn    As   Colo  Cole
## Ene 0.040  1.707  2.176 0.118 0.024 0.002 0.372 0.029 178600 74326
## Feb 0.065  7.207  7.595 0.324 0.081 0.005 0.611 0.126 247014 95332
## Mar 0.077 10.890 11.370 0.342 0.079 0.003 0.641 0.088 208035 90325</code></pre>
<p><strong>ANALISIS EXPLORATORIO</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="metodos.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Verificando si hay valores faltantes:</span></span>
<span id="cb8-2"><a href="metodos.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Detectando y graficando los % de datos perdidos</span></span>
<span id="cb8-3"><a href="metodos.html#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#No hay valores perdidos en ninguna variable</span></span>
<span id="cb8-4"><a href="metodos.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DataExplorer)</span>
<span id="cb8-5"><a href="metodos.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb8-6"><a href="metodos.html#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_missing</span>(datosc,<span class="at">ggtheme=</span><span class="fu">theme_minimal</span>())</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="metodos.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#estandarizamos los datos porque las variables se encuentran en diferentes escalas</span></span>
<span id="cb9-2"><a href="metodos.html#cb9-2" aria-hidden="true" tabindex="-1"></a> datosc <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(datosc))</span></code></pre></div>
<p><strong>CLUSTER JERARQUICO AGLOMERATIVO</strong></p>
<p>Distancia euclidiana y metodo de enlace Ward.D2</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="metodos.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-----------------------------------</span></span>
<span id="cb10-2"><a href="metodos.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#calculando la matriz de disimilaridad</span></span>
<span id="cb10-3"><a href="metodos.html#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="metodos.html#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="metodos.html#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="metodos.html#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="metodos.html#cb10-7" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">dist</span>(datosc, <span class="at">method =</span> <span class="st">&quot;euclidean&quot;</span>)</span>
<span id="cb10-8"><a href="metodos.html#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="metodos.html#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#el metodo ward.d2 ,para reconstruir la matriz distancia</span></span>
<span id="cb10-10"><a href="metodos.html#cb10-10" aria-hidden="true" tabindex="-1"></a>res.hc <span class="ot">&lt;-</span> <span class="fu">hclust</span>(d, <span class="at">method =</span> <span class="st">&quot;ward.D2&quot;</span> ) </span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="metodos.html#cb11-1" aria-hidden="true" tabindex="-1"></a>res.hc<span class="sc">$</span>merge</span></code></pre></div>
<pre><code>##       [,1] [,2]
##  [1,]  -10  -11
##  [2,]   -8   -9
##  [3,]   -1  -12
##  [4,]   -6    2
##  [5,]   -7    4
##  [6,]   -5    1
##  [7,]   -2   -3
##  [8,]    3    6
##  [9,]   -4    7
## [10,]    5    8
## [11,]    9   10</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="metodos.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#formacion de &quot;n&quot; cluster hasta 1 cluster</span></span>
<span id="cb13-2"><a href="metodos.html#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="metodos.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#observamos  que son 11 etapas:</span></span>
<span id="cb13-4"><a href="metodos.html#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="metodos.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co">#En la etapa 1 </span></span>
<span id="cb13-6"><a href="metodos.html#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">#el individuo 10 y el individuo 11 forman un cluster</span></span>
<span id="cb13-7"><a href="metodos.html#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="metodos.html#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co">#En la entapa 2</span></span>
<span id="cb13-9"><a href="metodos.html#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co">#el individuo 8 y el individuo 9 forman un cluster</span></span>
<span id="cb13-10"><a href="metodos.html#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="metodos.html#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">#y asi sucesivamente hasta llegar a la etapa 11 donde se  </span></span>
<span id="cb13-12"><a href="metodos.html#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co">#forma un solo  cluster</span></span></code></pre></div>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="metodos.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#estructura:</span></span>
<span id="cb14-2"><a href="metodos.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(res.hc)</span></code></pre></div>
<pre><code>## List of 7
##  $ merge      : int [1:11, 1:2] -10 -8 -1 -6 -7 -5 -2 3 -4 5 ...
##  $ height     : num [1:11] 1.55 1.9 2.54 3.36 3.95 ...
##  $ order      : int [1:12] 4 2 3 7 6 8 9 1 12 5 ...
##  $ labels     : chr [1:12] &quot;Ene&quot; &quot;Feb&quot; &quot;Mar&quot; &quot;Abr&quot; ...
##  $ method     : chr &quot;ward.D2&quot;
##  $ call       : language hclust(d = d, method = &quot;ward.D2&quot;)
##  $ dist.method: chr &quot;euclidean&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;hclust&quot;</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="metodos.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)<span class="co">#sin notacion cientifica</span></span></code></pre></div>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="metodos.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#distancia </span></span>
<span id="cb17-2"><a href="metodos.html#cb17-2" aria-hidden="true" tabindex="-1"></a> res.hc<span class="sc">$</span>height</span></code></pre></div>
<pre><code>##  [1]  1.554549  1.904331  2.540561  3.359679  3.950460  4.065524  4.075132
##  [8]  4.573464  7.031689  7.392952 18.178469</code></pre>
<p><strong>EL NUMERO DE CLUSTER</strong></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="metodos.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Hemos considerado que un cambio brusco seria de la etapa 9</span></span>
<span id="cb19-2"><a href="metodos.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co">#a la etapa 10,entonces el numero de cluster es 3</span></span>
<span id="cb19-3"><a href="metodos.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb19-4"><a href="metodos.html#cb19-4" aria-hidden="true" tabindex="-1"></a>alturas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">etapa=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>,<span class="at">distancia=</span>res.hc<span class="sc">$</span>height)<span class="co">#distancia </span></span>
<span id="cb19-5"><a href="metodos.html#cb19-5" aria-hidden="true" tabindex="-1"></a>alturas</span></code></pre></div>
<pre><code>##    etapa distancia
## 1      1  1.554549
## 2      2  1.904331
## 3      3  2.540561
## 4      4  3.359679
## 5      5  3.950460
## 6      6  4.065524
## 7      7  4.075132
## 8      8  4.573464
## 9      9  7.031689
## 10    10  7.392952
## 11    11 18.178469</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="metodos.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#screeplot con las distancias</span></span>
<span id="cb21-2"><a href="metodos.html#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="metodos.html#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(alturas) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x=</span>etapa,<span class="at">y=</span>distancia)  <span class="sc">+</span></span>
<span id="cb21-4"><a href="metodos.html#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_line</span>()  <span class="sc">+</span> </span>
<span id="cb21-5"><a href="metodos.html#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">15</span>)) <span class="sc">+</span> </span>
<span id="cb21-6"><a href="metodos.html#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">9</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb21-7"><a href="metodos.html#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="metodos.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir en 3 clusters</span></span>
<span id="cb22-2"><a href="metodos.html#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="metodos.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#La asignacion de cada elemento(mes) a cada cluster</span></span>
<span id="cb22-4"><a href="metodos.html#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="metodos.html#cb22-5" aria-hidden="true" tabindex="-1"></a>grp <span class="ot">&lt;-</span> <span class="fu">cutree</span>(res.hc, <span class="at">k =</span> <span class="dv">3</span>)</span>
<span id="cb22-6"><a href="metodos.html#cb22-6" aria-hidden="true" tabindex="-1"></a>grp </span></code></pre></div>
<pre><code>##  Ene  Feb  Mar  Abr  May  Jun  Ju!  Ago  Set  Oct  Nov Dic. 
##    1    2    2    2    1    3    3    3    3    1    1    1</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="metodos.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cluster1:</span></span>
<span id="cb24-2"><a href="metodos.html#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#enero,mayo,octubre,noviembre y diciembre</span></span>
<span id="cb24-3"><a href="metodos.html#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="metodos.html#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#cluster2:</span></span>
<span id="cb24-5"><a href="metodos.html#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">#febrero,marzo,abril</span></span>
<span id="cb24-6"><a href="metodos.html#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="metodos.html#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">#cluster3:</span></span>
<span id="cb24-8"><a href="metodos.html#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#junio,julio,agosto,setiembre</span></span></code></pre></div>
<p><strong>DEDONGRAMA</strong></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="metodos.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#visualizacion de los 3 cluster:</span></span>
<span id="cb25-2"><a href="metodos.html#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="metodos.html#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span></code></pre></div>
<pre><code>## Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="metodos.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_dend</span>(res.hc, <span class="at">k=</span><span class="dv">3</span>, <span class="at">cex =</span> <span class="fl">0.5</span>,</span>
<span id="cb27-2"><a href="metodos.html#cb27-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">k_colors =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>),   <span class="co"># Colores del arco iris</span></span>
<span id="cb27-3"><a href="metodos.html#cb27-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">color_labels_by_k =</span> <span class="cn">TRUE</span>, </span>
<span id="cb27-4"><a href="metodos.html#cb27-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">rect=</span>T)</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="metodos.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#conclusion del dendograma:</span></span>
<span id="cb28-2"><a href="metodos.html#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="metodos.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co">#estiage(fujo bajo del rio):</span></span>
<span id="cb28-4"><a href="metodos.html#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="metodos.html#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co">#junio,julio,agosto y setiembre</span></span>
<span id="cb28-6"><a href="metodos.html#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="metodos.html#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co">#transicion(incremento o disminucion del  flujo del rio):</span></span>
<span id="cb28-8"><a href="metodos.html#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="metodos.html#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co">#octubre, noviembre , diciembre , enero y mayo</span></span>
<span id="cb28-10"><a href="metodos.html#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="metodos.html#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co">#avenida(flujo alto de rio):</span></span>
<span id="cb28-12"><a href="metodos.html#cb28-12" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb28-13"><a href="metodos.html#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="co">#febrero, marzo y abril.</span></span>
<span id="cb28-14"><a href="metodos.html#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="metodos.html#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#En nuestro dendograma concluimos que los meses de transicion son </span></span>
<span id="cb28-16"><a href="metodos.html#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="co">#octubre, noviembre , diciembre , enero y mayo son meses que </span></span>
<span id="cb28-17"><a href="metodos.html#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co">#esta en un ritmo de cambio o bien sube el nivel del agua del rio </span></span>
<span id="cb28-18"><a href="metodos.html#cb28-18" aria-hidden="true" tabindex="-1"></a><span class="co">#o bien baja el nivel del agua del rio,es decir </span></span>
<span id="cb28-19"><a href="metodos.html#cb28-19" aria-hidden="true" tabindex="-1"></a><span class="co">#para que el nivel del agua del rio sea de flujo alto(avenida),en los</span></span>
<span id="cb28-20"><a href="metodos.html#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="co">#meses previos como enero,diciembre,noviembre,octubre tuvo que aumentar</span></span>
<span id="cb28-21"><a href="metodos.html#cb28-21" aria-hidden="true" tabindex="-1"></a><span class="co">#de poco a poco el nivel del agua hasta que febrero,marzo y abril </span></span>
<span id="cb28-22"><a href="metodos.html#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co">#(periodo flujo del rio es alto),luego llegando al mes de mayo </span></span>
<span id="cb28-23"><a href="metodos.html#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="co">#comienza a disminuir el nivel del agua de rio rimac este es el mes transicion</span></span>
<span id="cb28-24"><a href="metodos.html#cb28-24" aria-hidden="true" tabindex="-1"></a><span class="co">#despues en los meses posteriores  junio,julio,agosto y setiembre </span></span>
<span id="cb28-25"><a href="metodos.html#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co">#el nivel flujo del rio es bajo.</span></span></code></pre></div>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="metodos.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#conclusion del tesista:</span></span>
<span id="cb29-2"><a href="metodos.html#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="metodos.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#estiaje:</span></span>
<span id="cb29-4"><a href="metodos.html#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="metodos.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co">#mayo,junio,julio, agosto, setiembre y octubre   </span></span>
<span id="cb29-6"><a href="metodos.html#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="metodos.html#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#transicion(generan cambios inesperados o esperados):</span></span>
<span id="cb29-8"><a href="metodos.html#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="metodos.html#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#noviembre, diciembre y enero </span></span>
<span id="cb29-10"><a href="metodos.html#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="metodos.html#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co">#avenida:</span></span>
<span id="cb29-12"><a href="metodos.html#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="metodos.html#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co">#febrero, marzo y abril.</span></span></code></pre></div>
<p><strong>GRAFICA#ACP con CLUSTER</strong></p>
<p>GRAFICO 1</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="metodos.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Se puede apreciar que con 2 componentes retenemos 83.8% de la inercia total</span></span>
<span id="cb30-2"><a href="metodos.html#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb30-3"><a href="metodos.html#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(<span class="fu">list</span>(<span class="at">data =</span> datosc, <span class="at">cluster =</span> grp),</span>
<span id="cb30-4"><a href="metodos.html#cb30-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">palette =</span><span class="fu">c</span>(<span class="st">&quot;#DB1515&quot;</span>, <span class="st">&quot;#3722BF&quot;</span>, <span class="st">&quot;#D41AC4&quot;</span>) ,</span>
<span id="cb30-5"><a href="metodos.html#cb30-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">&quot;convex&quot;</span>, <span class="co"># Concentration ellipse</span></span>
<span id="cb30-6"><a href="metodos.html#cb30-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> T, <span class="co"># Avoid label overplotting (slow)</span></span>
<span id="cb30-7"><a href="metodos.html#cb30-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">show.clust.cent =</span> <span class="cn">FALSE</span>, <span class="at">ggtheme =</span> <span class="fu">theme_bw</span>())</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="metodos.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Juntando el archivo de &quot;datos&quot; con la columna de &quot;cluster&quot;</span></span>
<span id="cb31-2"><a href="metodos.html#cb31-2" aria-hidden="true" tabindex="-1"></a>datos.j <span class="ot">&lt;-</span> <span class="fu">cbind</span>(datosc,grp)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="metodos.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#convirtiendo en factor la varaible &quot;grp&quot; </span></span>
<span id="cb32-2"><a href="metodos.html#cb32-2" aria-hidden="true" tabindex="-1"></a>datos.j<span class="sc">$</span>grp <span class="ot">&lt;-</span> <span class="fu">factor</span>(datos.j<span class="sc">$</span>grp)</span>
<span id="cb32-3"><a href="metodos.html#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="metodos.html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Si deseamos exportar :</span></span>
<span id="cb32-5"><a href="metodos.html#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># write.csv(datos.j,&quot;Compras con Jerarquico Aglomerativo.csv&quot;)</span></span></code></pre></div>
<p><strong>Analisis de componenentes principales:</strong></p>
<p>ANALISIS EXPLORATORIO :</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="metodos.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="metodos.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorr</span>(datosc)</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="metodos.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Se puede observar  que entre las 24 variables, hay correlaciones muy altas , correlaciones altas  y correlaciones medias.</span></span>
<span id="cb36-2"><a href="metodos.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#esto podria traer problemas de multicolinealidad.</span></span></code></pre></div>
<p>Prueba de Esfericidad de Bartlett</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="metodos.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;psych&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     %+%, alpha</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="metodos.html#cb40-1" aria-hidden="true" tabindex="-1"></a>correlaciones<span class="ot">&lt;-</span> <span class="fu">corr.test</span>(datosc) <span class="co"># se crea la matriz de correlaciones  </span></span>
<span id="cb40-2"><a href="metodos.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co">#correlaciones$r                  # existe correlaciones  entre las variables   </span></span>
<span id="cb40-3"><a href="metodos.html#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rela)</span>
<span id="cb40-4"><a href="metodos.html#cb40-4" aria-hidden="true" tabindex="-1"></a>r<span class="ot">&lt;-</span><span class="fu">as.matrix</span>(correlaciones<span class="sc">$</span>r)</span>
<span id="cb40-5"><a href="metodos.html#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span>
<span id="cb40-6"><a href="metodos.html#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cortest.bartlett</span>(r,<span class="fu">nrow</span>(datosc))</span></code></pre></div>
<pre><code>## Warning in log(detR): Se han producido NaNs</code></pre>
<pre><code>## $chisq
## [1] NaN
## 
## $p.value
## [1] NaN
## 
## $df
## [1] 276</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="metodos.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prueba de Esfericidad de Bartlett</span></span>
<span id="cb43-2"><a href="metodos.html#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="metodos.html#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Prueba de Esfericidad de Bartlett</span></span>
<span id="cb43-4"><a href="metodos.html#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Ho: |Rp|=1 (las correlaciones teóricas entre cada par de variables es nulo)  </span></span>
<span id="cb43-5"><a href="metodos.html#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co">#H1: |Rp|≠1 (las correlaciones teóricas entre cada par de variables NO es nulo)</span></span>
<span id="cb43-6"><a href="metodos.html#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="metodos.html#cb43-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-8"><a href="metodos.html#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="co">#conclusion:</span></span>
<span id="cb43-9"><a href="metodos.html#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="metodos.html#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="co">#p-valor &lt; 0.05 ,</span></span>
<span id="cb43-11"><a href="metodos.html#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="co">#se rechaza la H0, se puede afirmar que las las correlaciones teóricas entre cada par de variables NO es nulo.</span></span>
<span id="cb43-12"><a href="metodos.html#cb43-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-13"><a href="metodos.html#cb43-13" aria-hidden="true" tabindex="-1"></a><span class="co">#en otras palabras nuestra matriz correlacion es diferente a la matriz identidad</span></span>
<span id="cb43-14"><a href="metodos.html#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="co">#podemos realizar analisis de componentes principales.</span></span></code></pre></div>
<p>Indicador Kaiser-Meyer-Olkinn KMO y MSA</p>
<pre><code>## Error in solve.default(r) : 
##   sistema es computacionalmente singular: número de condición recíproco = 2.02895e-19</code></pre>
<pre><code>## Kaiser-Meyer-Olkin factor adequacy
## Call: KMO(r = datosc)
## Overall MSA =  0.5
## MSA for each item = 
## Caud Temp   pH Turb   CE   OD   SD Akal   DI  Cls   so  N03  N02   PO   Cu   Al 
##  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5 
##   Fe   Mu   Pb   Cd   Zn   As Colo Cole 
##  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5</code></pre>
<p><strong>3.2Análisis de Componentes Principales con el paquete ade4</strong></p>
<p>CORROBORANDO LA GRAFICA 1</p>
<p>¿se podra explicar con 2 componentes todas las 24 variables ?</p>
<p>vamos a comprobar:</p>
<p>En el Grafico 1, se podia apreciar que con 2 componentes(retiene 83.8% de la inercia total) se podria explicar todas las 24 variables.</p>
<p>¿Cuantos componentes?</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="metodos.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ade4)</span>
<span id="cb46-2"><a href="metodos.html#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="metodos.html#cb46-3" aria-hidden="true" tabindex="-1"></a>acp <span class="ot">&lt;-</span> <span class="fu">dudi.pca</span>(datosc,<span class="at">scannf=</span><span class="cn">FALSE</span>,<span class="at">nf=</span><span class="fu">ncol</span>(datosc)) </span>
<span id="cb46-4"><a href="metodos.html#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(acp) </span></code></pre></div>
<pre><code>## Class: pca dudi
## Call: dudi.pca(df = datosc, scannf = FALSE, nf = ncol(datosc))
## 
## Total inertia: 24
## 
## Eigenvalues:
##     Ax1     Ax2     Ax3     Ax4     Ax5 
## 17.7541  2.3548  1.3683  0.9189  0.5800 
## 
## Projected inertia (%):
##     Ax1     Ax2     Ax3     Ax4     Ax5 
##  73.976   9.812   5.701   3.829   2.417 
## 
## Cumulative projected inertia (%):
##     Ax1   Ax1:2   Ax1:3   Ax1:4   Ax1:5 
##   73.98   83.79   89.49   93.32   95.73 
## 
## (Only 5 dimensions (out of 11) are shown)</code></pre>
<ul>
<li><p>Podemos observar que con 2 componenetes retenemos 83.79 % de la inercia total</p></li>
<li><p>Podemos observar que con 3 componenetes retenemos 89.49 % de la inercia total</p></li>
<li><p>Podemos observar que con 4 componenetes retenemos 93.32 % de la inercia total</p></li>
<li><p>Podemos observar que con 5 componenetes retenemos 95.73 % de la inercia total</p></li>
</ul>
<p><strong>CRITERIO DE LA MEDIA</strong></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="metodos.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores propios</span></span>
<span id="cb48-2"><a href="metodos.html#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="metodos.html#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co">#el criterio de la media:</span></span>
<span id="cb48-4"><a href="metodos.html#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="metodos.html#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co">#estamos trabajando con la matriz correlacion cada variable deberia retener  </span></span>
<span id="cb48-6"><a href="metodos.html#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="co">#1% de la inercia total , nos quedamos con los 3 primeros autovalores</span></span>
<span id="cb48-7"><a href="metodos.html#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co">#que son mayores a 1.</span></span>
<span id="cb48-8"><a href="metodos.html#cb48-8" aria-hidden="true" tabindex="-1"></a>acp<span class="sc">$</span>eig </span></code></pre></div>
<pre><code>##  [1] 17.75412281  2.35476144  1.36828719  0.91885927  0.58004727  0.40691705
##  [7]  0.24251967  0.16344726  0.11008407  0.06970343  0.03125052</code></pre>
<p>Conclusion:</p>
<p>3 componentes podemos explicar todas las 24 variables reteniendo 89.49 % de la inercia total.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="metodos.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># con 3 componetes podemos explicar las todas las 24  variables </span></span>
<span id="cb50-2"><a href="metodos.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># reteniendo 89.49% de la inercia total</span></span>
<span id="cb50-3"><a href="metodos.html#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">inertia.dudi</span>(acp)</span></code></pre></div>
<pre><code>## Inertia information:
## Call: inertia.dudi(x = acp)
## 
## Decomposition of total inertia:
##       inertia     cum  cum(%)
## Ax1  17.75412   17.75   73.98
## Ax2   2.35476   20.11   83.79
## Ax3   1.36829   21.48   89.49
## Ax4   0.91886   22.40   93.32
## Ax5   0.58005   22.98   95.73
## Ax6   0.40692   23.38   97.43
## Ax7   0.24252   23.63   98.44
## Ax8   0.16345   23.79   99.12
## Ax9   0.11008   23.90   99.58
## Ax10  0.06970   23.97   99.87
## Ax11  0.03125   24.00  100.00</code></pre>
<p>¿Como estan agrupadas las variables?</p>
<p>Nos basamos del criterio de las correlaciones</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="metodos.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlaciones entre las variables y los componentes</span></span>
<span id="cb52-2"><a href="metodos.html#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="metodos.html#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="metodos.html#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="metodos.html#cb52-5" aria-hidden="true" tabindex="-1"></a>acp<span class="sc">$</span>co[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)] </span></code></pre></div>
<pre><code>##           Comp1       Comp2       Comp3
## Caud -0.9856905 -0.01901796  0.07578045
## Temp -0.8575730  0.34464942 -0.26784995
## pH    0.1718367  0.32044552 -0.74235041
## Turb -0.9346113 -0.23625366  0.04170687
## CE    0.9441237 -0.27906809 -0.12008220
## OD   -0.2805474 -0.66047211  0.18988850
## SD    0.9217281 -0.33148387 -0.01124840
## Akal  0.9013802 -0.30784486 -0.16592703
## DI    0.9190383 -0.32601318 -0.17526601
## Cls   0.7834060 -0.44555826 -0.13405671
## so    0.9720223 -0.12524082 -0.11183695
## N03   0.8933136 -0.39175400 -0.02728335
## N02   0.8656142 -0.26140158 -0.19080927
## PO    0.9171172  0.02090579  0.18088859
## Cu   -0.9478302 -0.27917688  0.01341109
## Al   -0.9482153 -0.21768133  0.12213858
## Fe   -0.9559193 -0.19131422  0.14078444
## Mu   -0.9553130 -0.27329191 -0.04917357
## Pb   -0.9570670 -0.17625217  0.09659005
## Cd   -0.6493169 -0.55943616 -0.26456602
## Zn   -0.8225078 -0.45618080 -0.15216823
## As   -0.9213033 -0.15271183 -0.06553008
## Colo -0.8002671  0.02046972 -0.42279859
## Cole -0.7701392 -0.05606211 -0.45376503</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="metodos.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb54-2"><a href="metodos.html#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co">#componente1:#</span></span>
<span id="cb54-3"><a href="metodos.html#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb54-4"><a href="metodos.html#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="metodos.html#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="co">#caudal</span></span>
<span id="cb54-6"><a href="metodos.html#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="co">#temp</span></span>
<span id="cb54-7"><a href="metodos.html#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Turb</span></span>
<span id="cb54-8"><a href="metodos.html#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="co">#CE</span></span>
<span id="cb54-9"><a href="metodos.html#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="co">#SD</span></span>
<span id="cb54-10"><a href="metodos.html#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Akal</span></span>
<span id="cb54-11"><a href="metodos.html#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Di</span></span>
<span id="cb54-12"><a href="metodos.html#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Cls</span></span>
<span id="cb54-13"><a href="metodos.html#cb54-13" aria-hidden="true" tabindex="-1"></a><span class="co">#so</span></span>
<span id="cb54-14"><a href="metodos.html#cb54-14" aria-hidden="true" tabindex="-1"></a><span class="co">#NO3</span></span>
<span id="cb54-15"><a href="metodos.html#cb54-15" aria-hidden="true" tabindex="-1"></a><span class="co">#NO2</span></span>
<span id="cb54-16"><a href="metodos.html#cb54-16" aria-hidden="true" tabindex="-1"></a><span class="co">#PO</span></span>
<span id="cb54-17"><a href="metodos.html#cb54-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Cu</span></span>
<span id="cb54-18"><a href="metodos.html#cb54-18" aria-hidden="true" tabindex="-1"></a><span class="co">#Al</span></span>
<span id="cb54-19"><a href="metodos.html#cb54-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Fe</span></span>
<span id="cb54-20"><a href="metodos.html#cb54-20" aria-hidden="true" tabindex="-1"></a><span class="co">#Mu</span></span>
<span id="cb54-21"><a href="metodos.html#cb54-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Pb</span></span>
<span id="cb54-22"><a href="metodos.html#cb54-22" aria-hidden="true" tabindex="-1"></a><span class="co">#Cd</span></span>
<span id="cb54-23"><a href="metodos.html#cb54-23" aria-hidden="true" tabindex="-1"></a><span class="co">#Zn</span></span>
<span id="cb54-24"><a href="metodos.html#cb54-24" aria-hidden="true" tabindex="-1"></a><span class="co">#As</span></span>
<span id="cb54-25"><a href="metodos.html#cb54-25" aria-hidden="true" tabindex="-1"></a><span class="co">#Colo</span></span>
<span id="cb54-26"><a href="metodos.html#cb54-26" aria-hidden="true" tabindex="-1"></a><span class="co">#Cole</span></span>
<span id="cb54-27"><a href="metodos.html#cb54-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-28"><a href="metodos.html#cb54-28" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb54-29"><a href="metodos.html#cb54-29" aria-hidden="true" tabindex="-1"></a><span class="co">#componente2:#</span></span>
<span id="cb54-30"><a href="metodos.html#cb54-30" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb54-31"><a href="metodos.html#cb54-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-32"><a href="metodos.html#cb54-32" aria-hidden="true" tabindex="-1"></a><span class="co">#OD</span></span>
<span id="cb54-33"><a href="metodos.html#cb54-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-34"><a href="metodos.html#cb54-34" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb54-35"><a href="metodos.html#cb54-35" aria-hidden="true" tabindex="-1"></a><span class="co">#componente3:#</span></span>
<span id="cb54-36"><a href="metodos.html#cb54-36" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb54-37"><a href="metodos.html#cb54-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-38"><a href="metodos.html#cb54-38" aria-hidden="true" tabindex="-1"></a><span class="co">#pH</span></span></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="metodos.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Segunda forma</span></span>
<span id="cb55-2"><a href="metodos.html#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="metodos.html#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co">#podemos observar que todos las variables  estan asociados mas a la  </span></span>
<span id="cb55-4"><a href="metodos.html#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co">#dimension 1,excepto &quot;pH&quot; y &quot;OD&quot; que no se sabe con exactitud si pertenece</span></span>
<span id="cb55-5"><a href="metodos.html#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co">#a la dimension 1 o a la dimension2 de manera visual, pero con la matriz de</span></span>
<span id="cb55-6"><a href="metodos.html#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="co">#correlacion ya determinamos la variable &quot;pH&quot; pertenece al componente3 </span></span>
<span id="cb55-7"><a href="metodos.html#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co">#y la variable &quot;OD&quot; pertenece al componente2</span></span>
<span id="cb55-8"><a href="metodos.html#cb55-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-9"><a href="metodos.html#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="metodos.html#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb55-11"><a href="metodos.html#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(acp, <span class="at">col.var=</span><span class="st">&quot;steelblue&quot;</span>)<span class="sc">+</span><span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="metodos.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#biplot</span></span>
<span id="cb56-2"><a href="metodos.html#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="metodos.html#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb56-4"><a href="metodos.html#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_biplot</span>(acp, <span class="at">repel =</span> F,</span>
<span id="cb56-5"><a href="metodos.html#cb56-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">col.var =</span> <span class="st">&quot;steelblue&quot;</span>,</span>
<span id="cb56-6"><a href="metodos.html#cb56-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">col.ind =</span> <span class="st">&quot;black&quot;</span> )</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="metodos.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="do">###indicadores</span></span></code></pre></div>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="metodos.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Grafica de Valores propios - ScreePlot</span></span>
<span id="cb58-2"><a href="metodos.html#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="metodos.html#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co">#El primer componente retiene 74% de la inercia total</span></span>
<span id="cb58-4"><a href="metodos.html#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co">#El segundo componete retiene 9.8% de la inercia total</span></span>
<span id="cb58-5"><a href="metodos.html#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co">#El tercer componente retiene 5.7% de la inercia total</span></span>
<span id="cb58-6"><a href="metodos.html#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(acp, <span class="at">addlabels=</span><span class="cn">TRUE</span>, <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.3</span>,</span>
<span id="cb58-7"><a href="metodos.html#cb58-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">barfill=</span><span class="st">&quot;white&quot;</span>, <span class="at">barcolor =</span><span class="st">&quot;darkblue&quot;</span>,</span>
<span id="cb58-8"><a href="metodos.html#cb58-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">linecolor =</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">80</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() </span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="metodos.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scores o Puntuaciones de cada individuo</span></span>
<span id="cb59-2"><a href="metodos.html#cb59-2" aria-hidden="true" tabindex="-1"></a>acp<span class="sc">$</span>li[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]</span></code></pre></div>
<pre><code>##         Axis1      Axis2      Axis3      Axis4      Axis5      Axis6
## Ene -1.127415  1.2241429 -0.4215330 -0.3069565 -0.3072154  0.5909263
## Feb -7.321424 -1.5374149 -1.7252348 -0.2105345  0.3720162 -1.3205681
## Mar -8.892270 -1.2061457  1.2481771 -0.3727598 -0.6528833  0.9233570
## Abr -3.864966  2.5559978  1.5588401  1.1385843  0.8984151 -0.1376243
## May  1.653208 -0.3952227 -1.8173027  0.8938132  1.3875461  0.9216302
## Jun  3.526615 -1.9367091 -0.4606773  1.7958715 -0.9212378  0.2697353
## Ju!  3.869064 -1.6735475  0.6922911 -2.0693134  0.9202398  0.3494768
## Ago  3.572872 -1.2874593  1.1904835  0.2296801 -0.4971626 -0.6145975
## Set  2.750543 -0.5237799  1.5165983  0.4543415  0.3037690 -0.4558362
## Oct  2.683794  1.3317449 -0.4582014 -0.5302654 -0.2501176 -0.3660676
##           Axis7       Axis8       Axis9       Axis10      Axis11
## Ene -0.84209863 -0.02700337  0.59513448  0.137731734 -0.28618041
## Feb -0.13501618  0.03468823 -0.03902637  0.002647073 -0.06441864
## Mar  0.58541501 -0.14879593  0.06992054  0.007971082  0.08189278
## Abr -0.31046195  0.48237032 -0.25722398 -0.141189009  0.04003613
## May  0.09566827 -0.35219885  0.10107401 -0.032481919  0.19247022
## Jun  0.16195478  0.52714861 -0.22255381 -0.029503045 -0.18782676
## Ju! -0.14638363  0.41431959 -0.26683245 -0.103079184 -0.08997632
## Ago -0.46137750 -0.18005665  0.45333052 -0.377893091  0.25847307
## Set -0.02392110 -0.70148298 -0.21355210  0.542836370 -0.08427214
## Oct  0.63474890  0.61201151  0.34990784  0.422157105  0.20330096</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="metodos.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfica de individuos sobre el primer plano de componentes</span></span>
<span id="cb61-2"><a href="metodos.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">s.label</span>(acp<span class="sc">$</span>li,<span class="at">clabel=</span><span class="fl">0.7</span>,<span class="at">grid=</span><span class="cn">FALSE</span>,<span class="at">boxes=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="calidad_del_agua_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="objetivos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="applications.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["calidad_del_agua.pdf", "calidad_del_agua.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
